// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAppointment = `-- name: CreateAppointment :one

INSERT INTO appointments (
    availability_id,
    patient_id,
    user_id,
    turn_number,
    payment_token,
    price,
    booked_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING uuid
`

type CreateAppointmentParams struct {
	AvailabilityID int64
	PatientID      int64
	UserID         int64
	TurnNumber     int32
	PaymentToken   sql.NullString
	Price          int32
	BookedAt       time.Time
}

// ========================
// Queries for `appointments`
// ========================
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.AvailabilityID,
		arg.PatientID,
		arg.UserID,
		arg.TurnNumber,
		arg.PaymentToken,
		arg.Price,
		arg.BookedAt,
	)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments
WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAppointment, id)
	return err
}

const getAppointmentByUUID = `-- name: GetAppointmentByUUID :one
SELECT
    id,
    uuid,
    availability_id,
    patient_id,
    user_id,
    turn_number,
    payment_token,
    price,
    status,
    booked_at,
    created_at,
    updated_at
FROM appointments
WHERE uuid = $1
`

func (q *Queries) GetAppointmentByUUID(ctx context.Context, argUuid uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentByUUID, argUuid)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AvailabilityID,
		&i.PatientID,
		&i.UserID,
		&i.TurnNumber,
		&i.PaymentToken,
		&i.Price,
		&i.Status,
		&i.BookedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentsByAvailability = `-- name: GetAppointmentsByAvailability :many
SELECT
    id,
    uuid,
    availability_id,
    patient_id,
    user_id,
    turn_number,
    payment_token,
    price,
    status,
    booked_at,
    created_at,
    updated_at
FROM appointments
WHERE availability_id = $1
ORDER BY turn_number
`

func (q *Queries) GetAppointmentsByAvailability(ctx context.Context, availabilityID int64) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByAvailability, availabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.AvailabilityID,
			&i.PatientID,
			&i.UserID,
			&i.TurnNumber,
			&i.PaymentToken,
			&i.Price,
			&i.Status,
			&i.BookedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByUser = `-- name: GetAppointmentsByUser :many
SELECT
    id,
    uuid,
    availability_id,
    patient_id,
    user_id,
    turn_number,
    payment_token,
    price,
    status,
    booked_at,
    created_at,
    updated_at
FROM appointments
WHERE user_id = $1
ORDER BY booked_at DESC
`

func (q *Queries) GetAppointmentsByUser(ctx context.Context, userID int64) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.AvailabilityID,
			&i.PatientID,
			&i.UserID,
			&i.TurnNumber,
			&i.PaymentToken,
			&i.Price,
			&i.Status,
			&i.BookedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointments = `-- name: ListAppointments :many
SELECT
    id,
    uuid,
    turn_number,
    status,
    price,
    booked_at,
    patient_first_name,
    patient_last_name,
    doctor_id,
    doctor_first_name,
    doctor_last_name,
    specialty_id,
    specialty_name,
    date,
    start_time,
    end_time
FROM v_appointments_full
ORDER BY date, start_time, turn_number
`

func (q *Queries) ListAppointments(ctx context.Context) ([]VAppointmentsFull, error) {
	rows, err := q.db.QueryContext(ctx, listAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VAppointmentsFull
	for rows.Next() {
		var i VAppointmentsFull
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TurnNumber,
			&i.Status,
			&i.Price,
			&i.BookedAt,
			&i.PatientFirstName,
			&i.PatientLastName,
			&i.DoctorID,
			&i.DoctorFirstName,
			&i.DoctorLastName,
			&i.SpecialtyID,
			&i.SpecialtyName,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
