// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availabilities_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailability = `-- name: CreateAvailability :one

INSERT INTO availabilities (
  doctor_id,
  date,
  start_time,
  end_time,
  max_patients,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, doctor_id, date, start_time, end_time, max_patients, created_at, updated_at
`

type CreateAvailabilityParams struct {
	DoctorID    int64
	Date        pgtype.Date
	StartTime   pgtype.Time
	EndTime     pgtype.Time
	MaxPatients int32
}

// ========================
// Queries for `availabilities`
// ========================
func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.DoctorID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.MaxPatients,
	)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.MaxPatients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM availabilities
WHERE id = $1
`

func (q *Queries) DeleteAvailability(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAvailability, id)
	return err
}

const getAvailabilitiesByDoctorAndDate = `-- name: GetAvailabilitiesByDoctorAndDate :many
SELECT id, doctor_id, date, start_time, end_time, max_patients, created_at, updated_at
FROM availabilities
WHERE doctor_id = $1
  AND date = $2
`

type GetAvailabilitiesByDoctorAndDateParams struct {
	DoctorID int64
	Date     pgtype.Date
}

func (q *Queries) GetAvailabilitiesByDoctorAndDate(ctx context.Context, arg GetAvailabilitiesByDoctorAndDateParams) ([]Availability, error) {
	rows, err := q.db.Query(ctx, getAvailabilitiesByDoctorAndDate, arg.DoctorID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPatients,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityWithAppointmentsCount = `-- name: GetAvailabilityWithAppointmentsCount :one
SELECT 
    av.id, av.doctor_id, av.date, av.start_time, av.end_time, av.max_patients, av.created_at, av.updated_at,
    COUNT(a.id) AS current_appointments
FROM availabilities av
LEFT JOIN appointments a 
    ON a.availability_id = av.id
WHERE av.id = $1
GROUP BY av.id
`

type GetAvailabilityWithAppointmentsCountRow struct {
	ID                  int64
	DoctorID            int64
	Date                pgtype.Date
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	MaxPatients         int32
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	CurrentAppointments int64
}

func (q *Queries) GetAvailabilityWithAppointmentsCount(ctx context.Context, id int64) (GetAvailabilityWithAppointmentsCountRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilityWithAppointmentsCount, id)
	var i GetAvailabilityWithAppointmentsCountRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.MaxPatients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentAppointments,
	)
	return i, err
}

const listAvailabilities = `-- name: ListAvailabilities :many
SELECT 
  av.id, av.doctor_id, av.date, av.start_time, av.end_time, av.max_patients, av.created_at, av.updated_at,
  s.name AS specialty_name,
  d.first_name AS doctor_first_name,
  d.last_name AS doctor_last_name,
  d.prefix
FROM availabilities av
JOIN doctors d ON av.doctor_id = d.id
JOIN specialties s ON d.specialty_id = s.id
WHERE av.date >= $1
ORDER BY av.date, av.start_time
`

type ListAvailabilitiesRow struct {
	ID              int64
	DoctorID        int64
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	MaxPatients     int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	SpecialtyName   string
	DoctorFirstName string
	DoctorLastName  string
	Prefix          string
}

func (q *Queries) ListAvailabilities(ctx context.Context, date pgtype.Date) ([]ListAvailabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilities, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilitiesRow
	for rows.Next() {
		var i ListAvailabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPatients,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpecialtyName,
			&i.DoctorFirstName,
			&i.DoctorLastName,
			&i.Prefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilitiesByDoctorID = `-- name: ListAvailabilitiesByDoctorID :many
SELECT 
  av.id, av.doctor_id, av.date, av.start_time, av.end_time, av.max_patients, av.created_at, av.updated_at,
  s.name AS specialty_name,
  d.first_name AS doctor_first_name,
  d.last_name AS doctor_last_name,
  d.prefix,
  d.id AS doctor_id
FROM availabilities av
JOIN doctors d ON av.doctor_id = d.id
JOIN specialties s ON d.specialty_id = s.id
WHERE d.id = $1
  AND av.date >= $2
ORDER BY av.start_time
`

type ListAvailabilitiesByDoctorIDParams struct {
	ID   int64
	Date pgtype.Date
}

type ListAvailabilitiesByDoctorIDRow struct {
	ID              int64
	DoctorID        int64
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	MaxPatients     int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	SpecialtyName   string
	DoctorFirstName string
	DoctorLastName  string
	Prefix          string
	DoctorID_2      int64
}

func (q *Queries) ListAvailabilitiesByDoctorID(ctx context.Context, arg ListAvailabilitiesByDoctorIDParams) ([]ListAvailabilitiesByDoctorIDRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilitiesByDoctorID, arg.ID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilitiesByDoctorIDRow
	for rows.Next() {
		var i ListAvailabilitiesByDoctorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPatients,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpecialtyName,
			&i.DoctorFirstName,
			&i.DoctorLastName,
			&i.Prefix,
			&i.DoctorID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilitiesBySpecialtyID = `-- name: ListAvailabilitiesBySpecialtyID :many
SELECT 
  av.id, av.doctor_id, av.date, av.start_time, av.end_time, av.max_patients, av.created_at, av.updated_at,
  s.name AS specialty_name,
  d.first_name AS doctor_first_name,
  d.last_name AS doctor_last_name,
  d.prefix,
  d.id AS doctor_id
FROM availabilities av
JOIN doctors d ON av.doctor_id = d.id
JOIN specialties s ON d.specialty_id = s.id
WHERE s.id = $1
  AND av.date >= $2
ORDER BY av.date, av.start_time
`

type ListAvailabilitiesBySpecialtyIDParams struct {
	ID   int64
	Date pgtype.Date
}

type ListAvailabilitiesBySpecialtyIDRow struct {
	ID              int64
	DoctorID        int64
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	MaxPatients     int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	SpecialtyName   string
	DoctorFirstName string
	DoctorLastName  string
	Prefix          string
	DoctorID_2      int64
}

func (q *Queries) ListAvailabilitiesBySpecialtyID(ctx context.Context, arg ListAvailabilitiesBySpecialtyIDParams) ([]ListAvailabilitiesBySpecialtyIDRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilitiesBySpecialtyID, arg.ID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilitiesBySpecialtyIDRow
	for rows.Next() {
		var i ListAvailabilitiesBySpecialtyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPatients,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpecialtyName,
			&i.DoctorFirstName,
			&i.DoctorLastName,
			&i.Prefix,
			&i.DoctorID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailability = `-- name: UpdateAvailability :one
UPDATE availabilities
SET
  doctor_id = $2,
  date = $3,
  start_time = $4,
  end_time = $5,
  max_patients = $6,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, doctor_id, date, start_time, end_time, max_patients, created_at, updated_at
`

type UpdateAvailabilityParams struct {
	ID          int64
	DoctorID    int64
	Date        pgtype.Date
	StartTime   pgtype.Time
	EndTime     pgtype.Time
	MaxPatients int32
}

func (q *Queries) UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, updateAvailability,
		arg.ID,
		arg.DoctorID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.MaxPatients,
	)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.MaxPatients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
