// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: doctors_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctor = `-- name: CreateDoctor :one

INSERT INTO doctors (
    first_name,
    last_name,
    prefix,
    national_id,
    medical_license,
    specialty_code,
    description,
    education,
    phone,
    email,
    specialty_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id
`

type CreateDoctorParams struct {
	FirstName      string
	LastName       string
	Prefix         string
	NationalID     string
	MedicalLicense pgtype.Text
	SpecialtyCode  pgtype.Text
	Description    pgtype.Text
	Education      string
	Phone          string
	Email          pgtype.Text
	SpecialtyID    int64
}

// ========================
// Queries for `doctors`
// ========================
func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDoctor,
		arg.FirstName,
		arg.LastName,
		arg.Prefix,
		arg.NationalID,
		arg.MedicalLicense,
		arg.SpecialtyCode,
		arg.Description,
		arg.Education,
		arg.Phone,
		arg.Email,
		arg.SpecialtyID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM doctors WHERE id = $1
`

func (q *Queries) DeleteDoctor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDoctor, id)
	return err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT 
    d.id,
    d.first_name,
    d.last_name,
    d.prefix,
    d.medical_license,
    d.specialty_code,
    d.description,
    d.education,
    d.phone,
    d.email,
    s.name AS specialty_name
FROM doctors d
JOIN specialties s ON d.specialty_id = s.id
WHERE d.id = $1
`

type GetDoctorByIDRow struct {
	ID             int64
	FirstName      string
	LastName       string
	Prefix         string
	MedicalLicense pgtype.Text
	SpecialtyCode  pgtype.Text
	Description    pgtype.Text
	Education      string
	Phone          string
	Email          pgtype.Text
	SpecialtyName  string
}

func (q *Queries) GetDoctorByID(ctx context.Context, id int64) (GetDoctorByIDRow, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, id)
	var i GetDoctorByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Prefix,
		&i.MedicalLicense,
		&i.SpecialtyCode,
		&i.Description,
		&i.Education,
		&i.Phone,
		&i.Email,
		&i.SpecialtyName,
	)
	return i, err
}

const getDoctorIDByNationalID = `-- name: GetDoctorIDByNationalID :one
SELECT id
FROM doctors
WHERE national_id = $1
`

func (q *Queries) GetDoctorIDByNationalID(ctx context.Context, nationalID string) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorIDByNationalID, nationalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDoctors = `-- name: GetDoctors :many
SELECT 
    d.id,
    d.first_name,
    d.last_name,
    d.prefix,
    d.medical_license,
    d.specialty_code,
    d.description,
    d.education,
    d.phone,
    d.email,
    s.name AS specialty_name
FROM doctors d
JOIN specialties s ON d.specialty_id = s.id
`

type GetDoctorsRow struct {
	ID             int64
	FirstName      string
	LastName       string
	Prefix         string
	MedicalLicense pgtype.Text
	SpecialtyCode  pgtype.Text
	Description    pgtype.Text
	Education      string
	Phone          string
	Email          pgtype.Text
	SpecialtyName  string
}

func (q *Queries) GetDoctors(ctx context.Context) ([]GetDoctorsRow, error) {
	rows, err := q.db.Query(ctx, getDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDoctorsRow
	for rows.Next() {
		var i GetDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Prefix,
			&i.MedicalLicense,
			&i.SpecialtyCode,
			&i.Description,
			&i.Education,
			&i.Phone,
			&i.Email,
			&i.SpecialtyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoctorsBySpecialtyID = `-- name: GetDoctorsBySpecialtyID :many
SELECT 
    d.id,
    d.first_name,
    d.last_name,
    d.prefix,
    d.description,
    d.education,
    d.medical_license,
    d.specialty_code,
    d.phone,
    d.email,
    s.name AS specialty_name
FROM doctors d
JOIN specialties s ON d.specialty_id = s.id
WHERE s.id = $1
`

type GetDoctorsBySpecialtyIDRow struct {
	ID             int64
	FirstName      string
	LastName       string
	Prefix         string
	Description    pgtype.Text
	Education      string
	MedicalLicense pgtype.Text
	SpecialtyCode  pgtype.Text
	Phone          string
	Email          pgtype.Text
	SpecialtyName  string
}

func (q *Queries) GetDoctorsBySpecialtyID(ctx context.Context, id int64) ([]GetDoctorsBySpecialtyIDRow, error) {
	rows, err := q.db.Query(ctx, getDoctorsBySpecialtyID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDoctorsBySpecialtyIDRow
	for rows.Next() {
		var i GetDoctorsBySpecialtyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Prefix,
			&i.Description,
			&i.Education,
			&i.MedicalLicense,
			&i.SpecialtyCode,
			&i.Phone,
			&i.Email,
			&i.SpecialtyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctor = `-- name: UpdateDoctor :exec
UPDATE doctors
SET
    first_name = $2,
    last_name = $3,
    prefix = $4,
    medical_license = $5,
    specialty_code = $6,
    description = $7,
    phone = $8,
    email = $9,
    specialty_id = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateDoctorParams struct {
	ID             int64
	FirstName      string
	LastName       string
	Prefix         string
	MedicalLicense pgtype.Text
	SpecialtyCode  pgtype.Text
	Description    pgtype.Text
	Phone          string
	Email          pgtype.Text
	SpecialtyID    int64
}

func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) error {
	_, err := q.db.Exec(ctx, updateDoctor,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Prefix,
		arg.MedicalLicense,
		arg.SpecialtyCode,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.SpecialtyID,
	)
	return err
}
