// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AppointmentStatus string

const (
	AppointmentStatusPending   AppointmentStatus = "pending"
	AppointmentStatusConfirmed AppointmentStatus = "confirmed"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	AppointmentStatusExpired   AppointmentStatus = "expired"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type Appointment struct {
	ID             int64
	Uuid           uuid.UUID
	AvailabilityID int64
	PatientID      int64
	UserID         int64
	TurnNumber     int32
	PaymentToken   sql.NullString
	Price          int32
	Status         AppointmentStatus
	BookedAt       time.Time
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Availability struct {
	ID          int64
	DoctorID    int64
	Date        time.Time
	StartTime   time.Time
	EndTime     time.Time
	MaxPatients int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Doctor struct {
	ID             int64
	FirstName      string
	LastName       string
	Prefix         string
	NationalID     string
	MedicalLicense sql.NullString
	SpecialtyCode  sql.NullString
	Description    sql.NullString
	Education      string
	Phone          string
	Email          sql.NullString
	SpecialtyID    int64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Patient struct {
	ID         int64
	Uuid       uuid.UUID
	NationalID string
	FirstName  string
	LastName   string
	Phone      string
	Email      sql.NullString
	BirthDate  sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Pricing struct {
	DoctorID  int64
	Amount    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Specialty struct {
	ID               int64
	Name             string
	Description      sql.NullString
	ShortDescription sql.NullString
	Type             sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type User struct {
	ID           int64
	Uuid         uuid.UUID
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type VAppointmentsFull struct {
	ID               int64
	Uuid             uuid.UUID
	TurnNumber       int32
	Status           AppointmentStatus
	Price            int32
	BookedAt         time.Time
	PatientFirstName string
	PatientLastName  string
	DoctorID         int64
	DoctorFirstName  string
	DoctorLastName   string
	SpecialtyID      int64
	SpecialtyName    string
	Date             time.Time
	StartTime        time.Time
	EndTime          time.Time
}

type VAvailabilityDoctor struct {
	ID            int64
	Date          time.Time
	StartTime     time.Time
	EndTime       time.Time
	MaxPatients   int32
	DoctorID      int64
	FirstName     string
	LastName      string
	SpecialtyName string
}

type VAvailableSlot struct {
	AvailabilityID int64
	Date           time.Time
	StartTime      time.Time
	MaxPatients    int32
	Booked         int64
	Available      int32
}

type VPublicDoctor struct {
	ID            int64
	FirstName     string
	LastName      string
	Description   sql.NullString
	SpecialtyName string
}
