// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentStatus string

const (
	AppointmentStatusPending   AppointmentStatus = "pending"
	AppointmentStatusConfirmed AppointmentStatus = "confirmed"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	AppointmentStatusExpired   AppointmentStatus = "expired"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type Appointment struct {
	ID             int64
	Uuid           pgtype.UUID
	AvailabilityID int64
	PatientID      int64
	UserID         int64
	TurnNumber     int32
	PaymentToken   pgtype.Text
	Price          int32
	Status         AppointmentStatus
	BookedAt       pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Availability struct {
	ID          int64
	DoctorID    int64
	Date        pgtype.Date
	StartTime   pgtype.Time
	EndTime     pgtype.Time
	MaxPatients int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Doctor struct {
	ID             int64
	FirstName      string
	LastName       string
	Prefix         string
	NationalID     string
	MedicalLicense pgtype.Text
	SpecialtyCode  pgtype.Text
	Description    pgtype.Text
	Education      string
	Phone          string
	Email          pgtype.Text
	SpecialtyID    int64
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Patient struct {
	ID         int64
	Uuid       pgtype.UUID
	NationalID string
	FirstName  string
	LastName   string
	Phone      string
	Email      pgtype.Text
	BirthDate  pgtype.Date
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Pricing struct {
	DoctorID  int64
	Amount    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Specialty struct {
	ID               int64
	Name             string
	Description      pgtype.Text
	ShortDescription pgtype.Text
	Type             pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type User struct {
	ID           int64
	Uuid         pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type VAppointmentsFull struct {
	ID               int64
	Uuid             pgtype.UUID
	TurnNumber       int32
	Status           AppointmentStatus
	Price            int32
	BookedAt         pgtype.Timestamp
	PatientFirstName string
	PatientLastName  string
	DoctorID         int64
	DoctorFirstName  string
	DoctorLastName   string
	SpecialtyID      int64
	SpecialtyName    string
	Date             pgtype.Date
	StartTime        pgtype.Time
	EndTime          pgtype.Time
}

type VAvailabilityDoctor struct {
	ID            int64
	Date          pgtype.Date
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	MaxPatients   int32
	DoctorID      int64
	FirstName     string
	LastName      string
	SpecialtyName string
}

type VAvailableSlot struct {
	AvailabilityID int64
	Date           pgtype.Date
	StartTime      pgtype.Time
	MaxPatients    int32
	Booked         int64
	Available      int32
}

type VPublicDoctor struct {
	ID            int64
	FirstName     string
	LastName      string
	Description   pgtype.Text
	SpecialtyName string
}
