// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patients_query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPatient = `-- name: CreatePatient :one

INSERT INTO patients (
    uuid,
    national_id,
    first_name,
    last_name,
    phone,
    email,
    birth_date,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id
`

type CreatePatientParams struct {
	Uuid       uuid.UUID
	NationalID string
	FirstName  string
	LastName   string
	Phone      string
	Email      sql.NullString
	BirthDate  sql.NullTime
}

// ========================
// Queries for `patients`
// ========================
func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPatient,
		arg.Uuid,
		arg.NationalID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.BirthDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT
    id,
    uuid,
    national_id,
    first_name,
    last_name,
    phone,
    email,
    birth_date,
    created_at,
    updated_at
FROM patients
WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id int64) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NationalID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByNationalID = `-- name: GetPatientByNationalID :one
SELECT
    id,
    uuid,
    national_id,
    first_name,
    last_name,
    phone,
    email,
    birth_date,
    created_at,
    updated_at
FROM patients
WHERE national_id = $1
`

func (q *Queries) GetPatientByNationalID(ctx context.Context, nationalID string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByNationalID, nationalID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NationalID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET
    first_name = $2,
    last_name = $3,
    phone = $4,
    email = $5,
    birth_date = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, uuid, national_id, first_name, last_name, phone, email, birth_date, created_at, updated_at
`

type UpdatePatientParams struct {
	ID        int64
	FirstName string
	LastName  string
	Phone     string
	Email     sql.NullString
	BirthDate sql.NullTime
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRowContext(ctx, updatePatient,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.BirthDate,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NationalID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
