// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: specialties_query.sql

package db

import (
	"context"
	"database/sql"
)

const createSpecialty = `-- name: CreateSpecialty :exec

INSERT INTO specialties (
    name,
    description,
    short_description,
    type,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateSpecialtyParams struct {
	Name             string
	Description      sql.NullString
	ShortDescription sql.NullString
	Type             sql.NullString
}

// ========================
// Queries for `specialties`
// ========================
func (q *Queries) CreateSpecialty(ctx context.Context, arg CreateSpecialtyParams) error {
	_, err := q.db.ExecContext(ctx, createSpecialty,
		arg.Name,
		arg.Description,
		arg.ShortDescription,
		arg.Type,
	)
	return err
}

const deleteSpecialty = `-- name: DeleteSpecialty :exec
DELETE FROM specialties WHERE id = $1
`

func (q *Queries) DeleteSpecialty(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpecialty, id)
	return err
}

const getSpecialtyByID = `-- name: GetSpecialtyByID :one
SELECT 
    id,
    name,
    description,
    short_description,
    type
FROM specialties
WHERE id = $1
`

type GetSpecialtyByIDRow struct {
	ID               int64
	Name             string
	Description      sql.NullString
	ShortDescription sql.NullString
	Type             sql.NullString
}

func (q *Queries) GetSpecialtyByID(ctx context.Context, id int64) (GetSpecialtyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSpecialtyByID, id)
	var i GetSpecialtyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Type,
	)
	return i, err
}

const getSpecialtyByName = `-- name: GetSpecialtyByName :one
SELECT id
FROM specialties
WHERE name ILIKE $1
`

func (q *Queries) GetSpecialtyByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSpecialtyByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSpecialties = `-- name: ListSpecialties :many
SELECT 
    id,
    name,
    description,
    short_description,
    type
FROM specialties
ORDER BY name ASC
`

type ListSpecialtiesRow struct {
	ID               int64
	Name             string
	Description      sql.NullString
	ShortDescription sql.NullString
	Type             sql.NullString
}

func (q *Queries) ListSpecialties(ctx context.Context) ([]ListSpecialtiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpecialtiesRow
	for rows.Next() {
		var i ListSpecialtiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ShortDescription,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpecialty = `-- name: UpdateSpecialty :exec
UPDATE specialties
SET
    name = $2,
    description = $3,
    short_description = $4,
    type = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, short_description, type, created_at, updated_at
`

type UpdateSpecialtyParams struct {
	ID               int64
	Name             string
	Description      sql.NullString
	ShortDescription sql.NullString
	Type             sql.NullString
}

func (q *Queries) UpdateSpecialty(ctx context.Context, arg UpdateSpecialtyParams) error {
	_, err := q.db.ExecContext(ctx, updateSpecialty,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ShortDescription,
		arg.Type,
	)
	return err
}
