// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    uuid,
    email,
    username,
    password_hash,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, uuid, email, username, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Uuid         uuid.UUID
	Email        string
	Username     string
	PasswordHash string
}

// ========================
// Consultas para la tabla `users`
// ========================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Uuid,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE email = $1 AND id != $2
)
`

type ExistsUserByEmailParams struct {
	Email string
	ID    int64
}

func (q *Queries) ExistsUserByEmail(ctx context.Context, arg ExistsUserByEmailParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUserByEmail, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, email, username, password_hash
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64
	Uuid         uuid.UUID
	Email        string
	Username     string
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, email, username
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64
	Uuid     uuid.UUID
	Email    string
	Username string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getUserPasswordHashByEmail = `-- name: GetUserPasswordHashByEmail :one
SELECT password_hash
FROM users
WHERE email = $1
`

func (q *Queries) GetUserPasswordHashByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHashByEmail, email)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = $2,
    username = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, uuid, email, username, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       int64
	Email    string
	Username string
}

type UpdateUserProfileRow struct {
	ID        int64
	Uuid      uuid.UUID
	Email     string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.ID, arg.Email, arg.Username)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
